"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProcessDetail = ProcessDetail;
const jsx_runtime_1 = require("react/jsx-runtime");
function Field({ label, value }) {
    if (!value && value !== 0)
        return null;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "py-2 border-b border-gray-100 last:border-0", children: [(0, jsx_runtime_1.jsx)("dt", { className: "text-xs text-gray-500", children: label }), (0, jsx_runtime_1.jsx)("dd", { className: "text-sm text-gray-900 mt-0.5 break-all", children: String(value) })] }));
}
function ProcessDetail({ process, onClose }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: "fixed inset-0 z-50 flex flex-col justify-end bg-black/40", onClick: onClose, children: (0, jsx_runtime_1.jsxs)("div", { className: "bg-white rounded-t-2xl max-h-[85vh] flex flex-col", onClick: e => e.stopPropagation(), children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between px-4 pt-4 pb-3 border-b border-gray-200", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-base font-semibold text-gray-900 truncate pr-4", children: process.name }), (0, jsx_runtime_1.jsx)("button", { onClick: onClose, className: "text-gray-400 hover:text-gray-600 text-2xl leading-none", children: "\u00D7" })] }), (0, jsx_runtime_1.jsx)("div", { className: "overflow-y-auto flex-1 px-4 pb-6", children: (0, jsx_runtime_1.jsxs)("dl", { className: "mt-3", children: [(0, jsx_runtime_1.jsx)(Field, { label: "Package Type", value: process.packageType }), (0, jsx_runtime_1.jsx)(Field, { label: "Package Version", value: process.packageVersion }), (0, jsx_runtime_1.jsx)(Field, { label: "Folder", value: process.folderName }), (0, jsx_runtime_1.jsx)(Field, { label: "Target Framework", value: process.targetFramework }), (0, jsx_runtime_1.jsx)(Field, { label: "Robot Size", value: process.robotSize }), (0, jsx_runtime_1.jsx)(Field, { label: "Auto Update", value: process.autoUpdate ? 'Yes' : 'No' }), (0, jsx_runtime_1.jsx)(Field, { label: "Package Key", value: process.packageKey }), (0, jsx_runtime_1.jsx)(Field, { label: "Process ID", value: process.id }), (0, jsx_runtime_1.jsx)(Field, { label: "Folder Key", value: process.folderKey }), (0, jsx_runtime_1.jsx)(Field, { label: "Created", value: process.createdTime }), (0, jsx_runtime_1.jsx)(Field, { label: "Last Modified", value: process.lastModifiedTime }), process.description && ((0, jsx_runtime_1.jsxs)("div", { className: "py-2 border-b border-gray-100", children: [(0, jsx_runtime_1.jsx)("dt", { className: "text-xs text-gray-500", children: "Description" }), (0, jsx_runtime_1.jsx)("dd", { className: "text-sm text-gray-900 mt-0.5", children: process.description })] }))] }) })] }) }));
}
//# sourceMappingURL=ProcessDetail.js.map